### ISSUE TITLE
Where formal data dictionaries are publically available, point at them directly from the catalog?

### ISSUE THREAD

**Issue by ssilcot** [idn-au/catalogue-data#1]
AGIL is a great dataset to start with. I note it has a formalised (but not machine readable) data dictionary here: https://data.gov.au/data/storage/f/2013-12-02T03:02:16.736Z/agildataset-management-summary-2013-11.pdf which is dated 2013! Those contents really help a potential data user understand in depth what one might be able to do with that dataset.

Eventually I would like to see the catalog capable of pointing directly at such a DD, if one exists, as a kind of "in depth" descriptive resource, and to show the date of that resource (could that be added to our profile as an optional item?).

Risks with broken links using URLs of course (but we can detect that), so perhaps consider mining a copy of those sorts of really core files (there won't be many)?

**Comment by nicholascar** [comment]
In the current scope - metadata only for governance assessment - we do nothing here. In future scope (July+) we could say that certain types of datasets could/should have DDs and, when we know about them, my preference is to record the DD document as a related resource AND to then encode it as a DD in RDF, according to the Data Cube vocab: https://www.w3.org/TR/vocab-data-cube/#dsd-dsd
