### ISSUE TITLE
Contribute ANU researchers to Agents DB

### ISSUE THREAD

**Issue by Metaduck** [idn-au/catalogue-data#12]
12-Dec-23 Nick will attempt to include this in the workshop tomorrow

Nick will run through the process this afternoon (5/12/23)

Second pass underway

Filter the AERIES list of ANU people for indigenous researchers

**Comment by lalewis1** [comment]
TODO
- [ ] agree with @jamiefeiss on a format and holding location for input into the Agents DB
- [ ] get from Adegboyega a filtered list of authors from Aeries, or at least of method of filtering the list we already have.
- [ ] find and download an extract of registered indigenous corporations from https://www.oric.gov.au/catsi-act/about-public-register
- [ ] parse and serialize the oric extract into the agreed upon format for upload into the agentsDB

**Comment by lalewis1** [comment]
ORIC data on indigenous corporations can be downloaded from https://data.gov.au/data/dataset/aboriginal-and-torres-strait-islander-corporations-oric

**Comment by lalewis1** [comment]
~ 7000 indigenous corporations have been  extracted from the ORIC dataset and added to the agentsdb

**Comment by lalewis1** [comment]
a vocabulary about ORIC industries was also extracted and added to the IDN vocabs

**Comment by nicholascar** [comment]
Closing this to hand over other agent additions to new Issues
