### ISSUE TITLE
Review IDN Prez config

### ISSUE THREAD

**Issue by nicholascar** [idn-au/catalogue-data#19]
System: 
- [x] Speed up vocab rendering
- [x] Make PrezAPI & PrezUI version numbers visible
- [x] #25
    - [x] test: reg:status predicate missing label (e.g. https://data.idnau.org/v/vocab/vcb:idn-role-codes/c_rlcd:author)
    - [x] test: isDefinedBy (labelled badly) (e.g. https://data.idnau.org/v/vocab/vcb:idn-role-codes/c_rlcd:author)
- [x] RDF not rendered correctly for a Feature Collection - e.g. [AGIL Point Locations](https://data.idnau.org/s/datasets/pd:agil/collections/agil:point-locations/items)
- [x] RDF for Feature missing link to Feature Collection - e.g. [10 Mile Outstation](https://data.idnau.org/s/datasets/pd:agil/collections/agil:point-locations/items/agil:10MO)
- [x] #27
- [x] #23
- [x] #26
- [x] altr-ext & prez labels missing, e.g. https://data.idnau.org/profiles/altr-ext:alt-profile
    - [x] David will need to create labels for the altr-ext and prez ontologies. Put them in https://github.com/Kurrawong/semantic-background & https://github.com/RDFLib/prez/tree/main/prez/reference_data/context_ontologies
    - tracked at (https://github.com/RDFLib/prez/issues/231)
- [x] Show this Prez instance's OGC Test Suite results
- [x] Spatial data search results don't always render Feature's labels, e.g. AGIL Point Locations features https://data.idnau.org/s
    - tracked at (https://github.com/idn-au/idn-prez-theme/issues/2)

Vocabs:  
- [x] Deduplicate 2 x License vocabs - PR [12](https://github.com/idn-au/vocab-data/pull/12)
- [x] #24
    - fix labels in https://github.com/idn-au/vocab-data/blob/main/vocabs/licenses.ttl by putting the acronyms in `skos:notation` rather than `skos:prefLabel` and using the long name in the `skos:definition` for a new `skos:prefLabel` value
- [x] #35

Spatial:  
- [x] WKT data for NNTT dataset
- [x] Feature labels for NSW data
- [x] Search returns no results

Label fix steps:  

- add descriptions to label versions of background ontologies (https://github.com/Kurrawong/semantic-background/blob/main/scripts/extractor.py)
- reproduce *-labels.ttl for all ref onts (in https://github.com/Kurrawong/semantic-background/tree/main/labels)
- replace full ontology n-quads with just labelled versions from above in https://github.com/RDFLib/prez/tree/main/prez/reference_data/context_ontologies

**Comment by nicholascar** [comment]
Assigning to Lawson to fix some of the data errors.

Then must go to Jamie for system errors.

**Comment by lalewis1** [comment]
@jamiefeiss Might be time for me to hand this one off to you to fix some of the systems issues. I think I have resolved what I can from the data side.

There are also some prez fixes that have been merged, so If you can help me upgrade the version of prez then we can get those fixes coming across too.

**Comment by lalewis1** [comment]
Done
