### ISSUE TITLE
Pointing to data and/or to landing/provenance description pages -- AUSLANG example -- for consideration

### ISSUE THREAD

**Issue by ssilcot** [idn-au/catalogue-data#2]
Thinking out loud.... purpose -- to be very clear and distinct about what we are showing in the catalogue.

As at 2022-08-30 1.26pm: exploring http://idn.kurrawong.net/catalog/idndc/AUSLANG

Followed the "Access address" link which resolves to a download of the actual dataset. 

Checking under the hood (curl -H -v) the target url is https://collection.aiatsis.gov.au/datasets/austlang/001.csv 

The "ex:home" page is https://collection.aiatsis.gov.au/datasets/austlang/001 which is the provider's landing page, providing a data dictionary, a link to a live online search service and a link to the download csv format above.

There is also this: https://collection.aiatsis.gov.au/austlang/about which the data.gov.au LANDING page falsely describes as the "complete Austlang resource" -- it is not, but it is AIATSIS's complete DESCRIPTION of the context, meaning and provenance of the dataset! In fact. one could make a strong argument that unless this is read, one really doesn't understand at all what you are looking at.

There is also data.gov.au's activity list, showing recent changes: https://data.gov.au/data/dataset/activity/austlang-dataset-001

Starting to think we might need a small vocab to encode a range of relationships between the thing our catalog entry is describing and an associated resolvable uri! 

e.g.  

DESCRIPTIVE relationship: Contextual information (descriptive metadata, provenance) ABOUT the cataloged "dataset":
 * data.gov.au landing page
 * data.gov.au activity page (where relevant - calculable if you use this form of the ID: https://data.gov.au/data/dataset/austlang-dataset-001)
 * data providers' own general landing page
 * data providers detailed provenance "about" page: 

DERIVATIVE or INSTANCE relationship: An accessible distribution of the catalogued "dataset":
 * a computer file with a particular format (in this case csv)
 * a service end point 

I can even imagine a "USAGE" or "APPLICATION" type of relationship -- could point at resources in which dataset featured, or educational/capability resources in how to use it.

Open to discussion but in this PARTICULAR case (a really core "reference" dataset), I think the catalogue presentation would benefit by having multiple "Access address" entries with a clear typing of the nature of the association. Or perhaps even a way for the user to choose their "focus" ("I know what I want... just point me at the data/service" versus "what the hell is this all about, how can I use it?").

Sorry to ramble but devil in the detail here!

Plus issues with scalability... we perhaps need to be thinking about patterns in what "portals" like Trove or data.gov.au or RDA are doing? But that's another story.

**Comment by nicholascar** [comment]
For datasets that we are trying to capture governance information about, we don't really need any links to data/content/distributions at all so we would do nothing here!

> we might need a small vocab to encode a range of relationships between the thing our catalog entry is describing and an associated resolvable uri

In general this would be either Distribution metadata or DCAT's related resources. I'd hope we wouldn't have to implement our own vocab for this which must be a common requirement.
