### ISSUE TITLE
Add Metadata for ARIES/Thesis/OAIPMH data.

### ISSUE THREAD

**Issue by lalewis1** [idn-au/catalogue-data#39]
need to define datasets and vocabularies for all the data that i have extracted from ANU.

clean it up and add all neccessary metadata for proper rendering in PrezUI as we will soon need to upload it all to PrezUI hosted at NCI.

**Comment by Metaduck** [comment]
21-May Follow up with Tehri to check the modelling

**Comment by lalewis1** [comment]
done
