### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by ssilcot** [idn-au/catalogue-data#4]
http://idn.kurrawong.net/dataset/NDT/collections/determinations/items/DCD2014-003

This should return the "Brunette Downs" Feature from the NNTT Determinations dataset. Instead:

Internal Server Error

Sorry, something went wrong in server land.

ss 2022-09-30

**Comment by nicholascar** [comment]
Solved by fixing the NNTT dataset ID, see http://idn.kurrawong.net/dataset/NNTT/collections/determinations/items/DCD2014-003
