### ISSUE TITLE
How best to include DOIs/PIDs to publications derived from a dataset

### ISSUE THREAD

**Issue by ssilcot** [idn-au/catalogue-data#5]
These publications were derived from research using the KHRD database:

 * DOI (just a short note; includes a statement it's under permanent embargo: McCalman, J., Smith, L., Silcot, S., & Kippen, R. (2018). Koori health research database. figshare, https://doi.org/10.4225/03/5a9779c80f529 
 * DOI substantive research work arising from and good description of the provenance of the database: http://doi.org/10.1007/s12546-020-09253-x as listed in "Minerva" (Unimelb's research publications repo, here: https://minerva-elements.unimelb.edu.au/viewobject.html?cid=1&id=1517000)
 
SS to confirm it is appropriate to add this to the catalog entry as per DCAT2 spec (https://www.w3.org/TR/vocab-dcat-2/#examples-dataset-publication):
 
`dct:isReferencedBy <https://doi.org/10.4225/03/5a9779c80f529>;`
`dct:isReferencedBy <http://doi.org/10.1007/s12546-020-09253-x>;`

Check that CatPrez will appropriately render this relationship (does not need to resolve/fetch anything).

**Comment by nicholascar** [comment]
In general we wouldn't expect to capture outbound references from catalogues items to things derived from them, but the other way around. So, using `dct:reference` as the inverse of `dct:isReferencedBy`, catalogue entries for the publications could include:

```
<https://doi.org/10.4225/03/5a9779c80f529> dct:references <https://data.idnau.org/pid/KHRD> .
<http://doi.org/10.1007/s12546-020-09253-x> dct:references <https://data.idnau.org/pid/KHRD> .
```

So we would only store this info if we were recording the publications in a catalogue somewhere.
