### ISSUE TITLE
PID link showing instead of the Title in the IDN demo catalogue

### ISSUE THREAD

**Issue by Metaduck** [idn-au/catalogue-data#60]
### Current Behavior

[https://data.idnau.org/pid/WASC18democat](https://data.idnau.org/c/catalogs/pd:democat/resources) where "WASC18democat" is showing as a TITLE but when selected it takes you to the beginning of the resources page.

### Expected Behavior

I am not sure what metadata record is expected... Western Australian ...?

**Comment by jamiefeiss** [comment]
This was one of the resources that ISU wanted archived, so this behaviour is expected as the resource isn't resolvable anymore.
